# Generated by Django 2.1.5 on 2019-02-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('titile', models.CharField(max_length=40)),
                ('summary', models.TextField(max_length=200)),
            ],
        ),
    ]
